### PR TITLE
Fix prettier - remove double semicolons

### PR DESCRIPTION
**Pull request by jonathanadler**

### CODE REVIEW

**Review by EgoziE — APPROVED** [review]
Thanks for the contribution @jonathanadler.
Let's schedule a meeting to have a face-to-face review.

**Review by itaytay — COMMENTED** [review]
I'm not sure this is the right approach... 🤔 
Check [this](http://json.schemastore.org/prettierrc) out for more details

**Review by NitayRabi — COMMENTED** [review]
I think I would go with triple instead of 1 or 2. expected something else of you @jonathanadler ...

**Comment by mosheKerbel** [comment]
> I think I would go with triple instead of 1 or 2. expected something else of you @jonathanadler ...

Totally agree with Nitay here.

**Comment by jonathanadler** [comment]
😅  what a zubur

**Pull request closed without merging**
