### PR TITLE
[WIP][autocomplete] #WCN-3330: add aria-activedescendant for VO

### PR DESCRIPTION
**Pull request by 4alexandr**

### CODE REVIEW

**Comment by shlomitc** [comment]
why do you need to know about hover change?

**Comment by 4alexandr** [comment]
For accessibility - we need to mark current(hovered) option for VoiceOver utils. 
To do it we should use aria-activedescendant attribute with value eq to ID of hovered option.

**Comment by shlomitc** [comment]
Thanks for the PR. Please add missing tests

**Comment by shlomitc** [comment]
It's been stale for a while now so I'm closing. please re-open if you get to it.

thanks

**Pull request closed without merging**
