### PR TITLE
wix-ui-core|TagsList: fixed driver type for clickOnTagByIndex

### PR DESCRIPTION
**Pull request by liorMar**

### CODE REVIEW

**Comment by jonathanadler** [comment]
@zonzujiro 
Will this change break the santa build?
Are there any tests using this method?

**Comment by jonathanadler** [comment]
> @zonzujiro
> Will this change break the santa build?
> Are there any tests using this method?

Wait I take that back, it shouldn't break anything, right 🤔 ?

**Comment by zonzujiro** [comment]
@jonathanadler as far as I remember, this method, in general, not used anywhere.

**Comment by jonathanadler** [comment]
> @jonathanadler as far as I remember, this method, in general, not used anywhere.

Cool, so i'm merging

**Pull request merged**
