### PR TITLE
Revert "Migrate <Popover/> to the new <ClickOutside/>"

### PR DESCRIPTION
**Pull request by mykas**
Reverts wix/wix-ui#1544

### CODE REVIEW

**Comment by OriMarron** [comment]
@mykas why did you revert? will you migrate to new version again?

**Comment by mykas** [comment]
It caused our users builds to fail on Dropdown changes. The popover side will be extracted to a separate pr and for dropdown we will need to do a breaking change at some time in the future.

**Comment by OriMarron** [comment]
haha funny 😀
we broke after the initial PR, made a fix, and now broke again for the revert.
but no problem, I reverted as well.

**Comment by mykas** [comment]
sorry :D

**Pull request merged**
