### PR TITLE
<Avatar /> - remove grapheme-splitter dep

### PR DESCRIPTION
**Pull request by jjaskulis**
Removing not needed feature and dependency to decrease bundle size.

https://jira.wixpress.com/browse/DSM-1062

### CODE REVIEW

**Comment by mykas** [comment]
Wait, I specifically remembered that we had a user wanting this feature 🤔

**Comment by mykas** [comment]
Can you double check with the task owner if this is still relevant? https://github.com/wix/wix-ui-tpa/issues/145

**Comment by jjaskulis** [comment]
> Can you double check with the task owner if this is still relevant? [wix/wix-ui-tpa#145](https://github.com/wix/wix-ui-tpa/issues/145)

@mykas I see, thanks for bringing attention to this. Will discuss this over with the task owner.

**Comment by jonathanadler** [comment]
@mykas 
We talked about this here: https://github.com/wix/wix-ui/pull/1510

The issue opened in wix-ui-tpa was just something that the developers thought it would be nice to have.
It did not come from a user's request, or a bug.

At the moment we don't see any reason to have this feature, since there isn't a real case for it, and the 3rd party package weighs too much.

I think it's ok to remove, furthermore, I think the tests should still pass (except the test with the emoji - which @jjaskulis you should probably remove in this PR)

**Comment by jjaskulis** [comment]
> @mykas
> We talked about this here: #1510
> 
> The issue opened in wix-ui-tpa was just something that the developers thought it would be nice to have.
> It did not come from a user's request, or a bug.
> 
> At the moment we don't see any reason to have this feature, since there isn't a real case for it, and the 3rd party package weighs too much.
> 
> I think it's ok to remove, furthermore, I think the tests should still pass (except the test with the emoji - which @jjaskulis you should probably remove in this PR)

@jonathanadler updated the test spec

**Comment by mykas** [comment]
@jonathanadler fine by me! As long as there isn't more dependencies like wix-ui-santa (God help us)

**Comment by jonathanadler** [comment]
I see that the build is failing on lint issues.
But I also think they're not related to the PR itself 🤔

**Review by jonathanadler — APPROVED** [review]

**Comment by jjaskulis** [comment]
@jonathanadler did a rebase, could you re-approve?

**Review by jonathanadler — APPROVED** [review]
Awesome thanks!

**Pull request merged**
