### PR TITLE
bump playable to 2.11.1

### PR DESCRIPTION
**Pull request by mokhovyk**

### CODE REVIEW

**Review by BrooklynKing — APPROVED** [review]

**Comment by shlomitc** [comment]
Hey!

please take a minute to sign your commits in order for them to pass in the CI. https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

**Comment by mokhovyk** [comment]
> Hey!
> 
> please take a minute to sign your commits in order for them to pass in the CI. https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits

Hey, the commit was signed

**Comment by shlomitc** [comment]
image
I don't see that it's signed. it should have a `Verified` badge next to it like here:
image

**Comment by mokhovyk** [comment]
> image
> I don't see that it's signed. it should have a `Verified` badge next to it like here:
> image

Could you assist with GPG sign. it is not obvious, I got an error
```
error: gpg failed to sign the data
fatal: failed to write commit object
```
Here is my global git config:
```
user.name=Andrii Mokhovyk
user.email=andriimo@wix.com
user.signingkey=<MYKEY>
commit.gpgsign=true
gpg.program=gpg
```
I checked that I use the same user.name and user.email as in signing key. Using gpg2. 

Checked lots of info on stackoverflow but nothing helped me

**Comment by mokhovyk** [comment]
> image
> I don't see that it's signed. it should have a `Verified` badge next to it like here:
> image

Done :) it wasn't obvious, need to install GPG suite (brew install is not enough)

**Comment by mokhovyk** [comment]
I doubt this is a good idea, but we can add feature owners to this list, 
Illya Veklenko - Top Bar package
Andrii Mokhovyk - editor View
Oleksii Makodzeba - search package

**Comment by shlomitc** [comment]
@mokhovyk - if you can add to the explanation doc what was missing, that would be great

**Comment by mokhovyk** [comment]
@BrooklynKing see comment above, could you add doc?

**Comment by BrooklynKing** [comment]
In `2.11.1` version we fixed corrupted icon for volume control. You can find for info here https://github.com/wix/playable/releases/tag/v2.11.1

**Pull request merged**
