### PR TITLE
Mocha runner: use for unit tests, again

### PR DESCRIPTION
**Pull request by alisey**
After working around the type definitions issue and adding source maps I think we're ready. Just need to see it passing on CI.

### CODE REVIEW

**Comment by alisey** [comment]
@shlomitc Duh!

```
[npm test] Error: Failed to launch chrome!
[15:51:13][npm test] [0620/155112.310818:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! 
Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

I wonder what's the deal with our CI servers. It passed fine before, who can I talk to about this?

**Comment by shlomitc** [comment]
try running again, might work

**Comment by lbelinsk** [comment]
revert?

**Comment by alisey** [comment]
Let me try to disable sandbox, if that fails too then let's revert.

**Comment by shlomitc** [comment]
I think it passed in CI

**Comment by alisey** [comment]
Great if it did, I currently don't have VPN to check, will look into the sandboxing issues tomorrow. Puppeteer documentation says that on Travis it must be used with `--no-sandbox` parameter. It's a mystery how it passed the first time then.

**Pull request merged**
