### PR TITLE
Removed HBox and VBox

### PR DESCRIPTION
**Pull request by alisey**
I've checked that HBox and VBox are not used in projects using wix-ui-core.

### CODE REVIEW

**Comment by WixBuildServer** [comment]
View storybook at: https://wix-wix-ui-icons-common-pr-480.surge.sh

**Comment by WixBuildServer** [comment]
View storybook at: https://wix-wix-ui-core-pr-480.surge.sh

**Comment by lbelinsk** [comment]
Maybe I am not in the loop, but when did we get the decision to remove them?
The backoffice HBox is being used by businessManager, so how is it possible to move this?

**Comment by lbelinsk** [comment]
oh, just saw the mail. So just see this: 
https://github.com/search?q=org%3Awix-private+HBox+wix-style-react&type=Code
wix-style-react is proxying HBox from backoffice which proxies from core.

**Comment by alisey** [comment]
@lbelinsk wix-ui-backoffice doesn't actually proxy from wix-ui-core, it uses its own copy of JSS HBox:
https://github.com/wix/wix-ui-backoffice/search?utf8=%E2%9C%93&q=HBox

**Comment by lbelinsk** [comment]
I thought @Zombiefruit already added the stylable components to the backoffice, so in that case ok..

**Comment by shlomitc** [comment]
@alisey - can you make a PR to `wix-ui-backoffice` with these components, please?

**Comment by alisey** [comment]
@shlomitc added to the backoffice here: https://github.com/wix/wix-ui-backoffice/pull/129

**Pull request merged**
