### PR TITLE
Update React versions and make linting pass

### PR DESCRIPTION
**Pull request by Zombiefruit**

### CODE REVIEW

**Comment by Zombiefruit** [comment]
Hey, another solution is to set the `reactStrictModeCompliant` flag on the tooltip and popover metadata to false. Then sanity will pass on those components, and we can update versions

**Comment by mykas** [comment]
Thats a great idea! Thanks

**Comment by Zombiefruit** [comment]
Cool! Glad to hear it :)

**Comment by Zombiefruit** [comment]
Closing this PR: easier to make the required changes in ui-autotools. Referencing this issue for those from the future: https://github.com/Microsoft/TypeScript/issues/28009. When this problem is solved, it  will be easier to migrate wix-ui-core to use `esModuleInterop = true`.

**Pull request closed without merging**
