### PR TITLE
Updated Mobile and New Tablet icons

### PR DESCRIPTION
**Pull request by ZilvinasMaciulis**

### CODE REVIEW

**Comment by TalZa1810** [comment]
Hi @ZilvinasMaciulis ,
I see that you've added 2 new icons. Please add the meta data of them.

Thanks

**Comment by ZilvinasMaciulis** [comment]
Will do

**Comment by shlomitc** [comment]
@TalZa1810 - what's the status of this PR?

**Review by TalZa1810 — DISMISSED** [review]

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-icons-common.pr_1989/

**Pull request merged**
