### PR TITLE
scoped packages

### PR DESCRIPTION
**Pull request by mykas**

### CODE REVIEW

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-icons-common**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-icons-common.pr_2049/

**Comment by argshook** [comment]
maybe let's update each package in separate PR? it's more effort but safer

**Comment by mykas** [comment]
But its just @wix/yoshi scope 🤔

**Comment by argshook** [comment]
> But its just @wix/yoshi scope

ok, but if something breaks then you debug :D

**Comment by mykas** [comment]
yes :D thats the idea!

**Review by argshook — APPROVED** [review]

**Pull request merged**
