### PR TITLE
New directions for chevron large

### PR DESCRIPTION
**Pull request by ZilvinasMaciulis**

### CODE REVIEW

**Comment by TalZa1810** [comment]
@ZilvinasMaciulis 
I'm not sure about the naming.. `ChevronDownLargeSmall`? two suffixes?

**Comment by ZilvinasMaciulis** [comment]
Yes. We have several chevron icon sizes for the same artboard. Meaning that both 24 and 18 artboards can contain large and small chevrons.

**Comment by ZilvinasMaciulis** [comment]
image

here is some visual explanation

**Comment by TalZa1810** [comment]
Apparently we have already some icons with the same naming:
- `RectangleLargeSmall` 
- `TriangleLargeSmall`
- `CircleLargeSmall`

 It's very confusing IMO. 

FYI @shlomitc

**Comment by shlomitc** [comment]
I agree it is confusing. let's try to find a better convention

**Pull request merged**
