### PR TITLE
Older version of Node doesn't support stdout.clearLine, use readline

### PR DESCRIPTION
**Pull request by alisey**

### CODE REVIEW

**Comment by shlomitc** [comment]
CI is still failing

**Comment by alisey** [comment]
CI is failing because of e2e, something about storybook? `TimeoutError: Cannot find Checkbox`.

**Comment by alisey** [comment]
This is a tiny change that I'd like to get out as soon as possible. New tests already have been added that fail in browser.

**Comment by shlomitc** [comment]
please update branch with master to make PR pass

**Pull request merged**
