### PR TITLE
Two New and two updated icons.

### PR DESCRIPTION
**Pull request by ZilvinasMaciulis**

### CODE REVIEW

**Comment by mosheKerbel** [comment]
@ZilvinasMaciulis plz update the [metadata](https://github.com/wix/wix-ui/blob/ZilvinasMaciulis-patch-6/packages/wix-ui-icons-common/src/classic-editor/general/metadata.ts) as well, so the new icons will be reflected in storybook.

**Review by mosheKerbel — APPROVED** [review]

**Comment by mosheKerbel** [comment]
just to verify - these changes are for wsr icons right? not base-ui

**Comment by WixBuildServer** [comment]
### 🤖 Hi, I'm #Janet!

  A deploy preview of your PR was successfully released 🖼.

  Project Name: **wix-ui-icons-common**

  You can find it under one of the following URLs:
  * https://bo.wix.com/pages/wix-ui-icons-common.pr_2061/

**Comment by ZilvinasMaciulis** [comment]
@mosheKerbel Yes these icons are for WSR only

**Pull request merged**
