### PR TITLE
<PreviewWidget/>, <MobilePreviewWidget/>, <BrowserPreviewWidget/>- adding types to testkits

### PR DESCRIPTION
**Pull request by TalZa1810**
Adding types to `<PreviewWidget/>`, `<MobilePreviewWidget/>` and `<BrowserPreviewWidget/>`.

### CODE REVIEW

**Comment by shlomitc** [comment]
If it’s a new component - why not to create the types next to the component?

**Comment by TalZa1810** [comment]
I've added the types next to the Components. We talked about this today in the meeting. Moshe asked us to add these as a temporary solution for all new components until we merge all types to WSR.

**Comment by shlomitc** [comment]
we're adding here types for existing components because we don't want to break users, but I think that for new components, types should be in `wsr` from day one (that's why we want to add it to the generator)

**Comment by mosheKerbel** [comment]
> we're adding here types for existing components because we don't want to break users, but I think that for new components, types should be in `wsr` from day one (that's why we want to add it to the generator)

@shlomitc Tal did added the types next to the component
this is just an addition for `wsr-types` so our testers would still be able to import the teskits, because the testkits d.ts over-ride the ones in wix-style-react.

**Comment by shlomitc** [comment]
so it looks like an issue needs to be solved.
Can't we declare this module as a union for `any` with the testkits that are here?

we can merge it anyway if that's how it works now

**Comment by mosheKerbel** [comment]
> so it looks like an issue needs to be solved.
> Can't we declare this module as a union for `any` with the testkits that are here?
> 
> we can merge it anyway if that's how it works now

no, once you declare this kind of type
`declare module 'wix-style-react/dist/testkit/enzyme'`
and import it from a project, it completly over-ride the old d.ts, it does not make a union of the two.

**Comment by mosheKerbel** [comment]
@TalZa1810 plz add it also for the other testkits

**Pull request merged**
