### PR TITLE
DektopDisabled & VideoCameraDisabled fixes

### PR DESCRIPTION
**Pull request by ZilvinasMaciulis**

### CODE REVIEW

**Review by dovilel — APPROVED** [review]

**Comment by ZilvinasMaciulis** [comment]
@TalZa1810 Hi! I need your magic powers to merge this PR

**Review by TalZa1810 — APPROVED** [review]

**Comment by ZilvinasMaciulis** [comment]
@mykas can you please approve and merge these icons. Tal Zaidman has some kind of technical issues and can't do it at the moment

**Comment by ZilvinasMaciulis** [comment]
@mykas sorry to bother but I need your approval for this one aswell

**Comment by mykas** [comment]
@ZilvinasMaciulis this change it seems its modifying existing icons. Can you tell me about the impact of this change? How big is the change?

**Comment by ZilvinasMaciulis** [comment]
@mykas DesktopDisabled & VideoCameraDisabled have been uploaded as new icons a few weeks ago. Yesterday Dovile discovered that the icons aren't aligned to the container centered (they should be). This was due to some Sketch artifacts left after exported SVG. I fixed export issues and now I need to merge SVGs. This will result in updated (fixed) icon graphics for all the users that are using this icon currently. Nothing changes in the icon naming.

**Comment by mykas** [comment]
I can't tell though from the applitools screenshot that it is centered now correctly. From the changes it looks it went down from the top left corner to bottom right corner 🤷‍♂️

**Pull request merged**
