### PR TITLE
change image-client-api package to @wix/image-client-api

### PR DESCRIPTION
**Pull request by eranshabi**

### CODE REVIEW

**Comment by eranshabi** [comment]
> This change should not be approved. wix-ui-core is an open source package and this takes a private registry package. Why do you need this change?

Because in `image-client-api` there are some `const`s that get inside our bundle

**Comment by shlomitc** [comment]
What do you mean by some `const`s? what's the difference between the two packages?
They should be exactly the same package, only published to the public registry

**Comment by eranshabi** [comment]
image-client-api was fixed so if you use latest you won't publish es6 code in the next version you publish

**Comment by shlomitc** [comment]
Thanks!

**Pull request closed without merging**
