### PR TITLE
skipPropsWithoutDoc

### PR DESCRIPTION
**Pull request by kobiburnley**
We use `react-storybook-utils` with TypeScript, and we would like to filter out props that don't have a description

### CODE REVIEW

**Comment by argshook** [comment]
Hey there @kobiburnley, pardon for such a late response, i had a whole
month of vacation without any javascript!

Unfortunately, i cannot accept this PR, because it would break existing
users who depend on getting undocumented props in the output. This is
for sure the case in wix-design-systems, for example. It's also
indicated by red tests in the build of this PR.

To prevent breaking existing users, this functionality should be
configurable. Here's a PR addressing exactly that: https://github.com/wix/wix-ui/pull/2142

With it, you'd be able to use `gatherAll(path, { skipPropsWithoutDoc: true })`

Let me know if this would work for you and i'll release that change
under new version.

Thanks and sorry for such a long delay!

**Comment by kobiburnley** [comment]
@argshook is there a way to pass this option via a story using `wix-storybook-utils` webpack plugin?

**Comment by argshook** [comment]
> @argshook is there a way to pass this option via a story config using `wix-storybook-utils` webpack plugin?

ah, you said you use `react-autodocs-utils`, so i assumed you use it directly.

At the moment no, there is no way, but with the aforementioned PR it's trivial to implement

**Comment by kobiburnley** [comment]
> We use `react-storybook-utils` with TypeScript, and we would like to filter out props that don't have a description

`react-storybook-utils`

**Comment by argshook** [comment]
hey @kobiburnley, i have released new versions of both
`react-autodocs-utils` and `wix-storybook-utils`.

You should be able to use now `skipPropsWithoutDoc` setting through the
`WixStorybookWebpackPlugin` like so:

```js
new WixStorybookWebpackPlugin({
  // ...
  parserOptions: {
    skipPropsWithoutDoc: true,
  },
  // ...
}),
```

make sure to use latest version of `wix-storybook-utils`: 4.0.30

**Pull request closed without merging**
