### PR TITLE
Uploaded section icon

### PR DESCRIPTION
**Pull request by Zohar-Telor**
now with the actual svg

### CODE REVIEW

**Comment by TalZa1810** [comment]
```
  {
    "title": "Section",
    "category": "Components",
    "description": "",
    "tags": [],
    "sizes": {
      "24": "Section"
    }
  }
```

This is the icon without svg so the titles should be the same. you can either change the title of the icon or change the meta data which was already merged

**Comment by Zohar-Telor** [comment]
@TalZa1810 added section icon

**Comment by TalZa1810** [comment]
relevat PR which was missing the svg for referece: https://github.com/wix/wix-ui/pull/2190/files

**Review by TalZa1810 — APPROVED** [review]

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-icons-common**
Commit: **6b1f549cd3cd2fa17dbff7a8b54ba03d3b62d509**

You can find it under one of the following URLs:
* https://bo.wix.com/pages/wix-ui-icons-common.pr_2200/

**Pull request merged**
