### PR TITLE
Added isSelectable method to DropdownOption.driver

### PR DESCRIPTION
**Pull request by tkvlnk**

### CODE REVIEW

**Comment by shlomitc** [comment]
thanks - can you please add also a test that uses this method?

**Comment by tkvlnk** [comment]
> thanks - can you please add also a test that uses this method?

Hi @shlomitc 
I've added asserts here
packages/wix-ui-core/src/components/dropdown-option/DropdownOption.spec.tsx

should I add more?

**Comment by shlomitc** [comment]
looks good. Please make sure that your PRs are [signed](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits), otherwise the PR build will not start

**Comment by tkvlnk** [comment]
> looks good. Please make sure that your PRs are [signed](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CREATE_PR.md#sign-commits), otherwise the PR build will not start

done

**Pull request merged**
