### PR TITLE
[Address-Input] Adding appendTo prop for the use case that an AddressInput component inside of a modal, and the options element should overflow out of the modal

### PR DESCRIPTION
**Pull request by barboaron**
…

### CODE REVIEW

**Comment by env-github-token** [comment]
### 🤖 Hi, I'm #Janet!

A deploy preview of your PR was successfully released 🖼.

Project Name: **wix-ui-core**

You can find it under one of the following URLs:
* https://wix-pages.com/wix-ui-core.pr_2175/

**Review by jonathanadler — COMMENTED** [review]
Looks good 👌 

But I think it would be a good idea to add a test ensuring this prop exists.
Otherwise someone might remove it and break your app.

**Comment by barboaron** [comment]
> Looks good 👌
> 
> But I think it would be a good idea to add a test ensuring this prop exists.
> Otherwise someone might remove it and break your app.

Added :) @jonathanadler

**Comment by jonathanadler** [comment]
> > Looks good 👌
> > But I think it would be a good idea to add a test ensuring this prop exists.
> > Otherwise someone might remove it and break your app.
> 
> Added :) @jonathanadler

Maybe add to `AddressInput` as well 😬

**Review by jonathanadler — APPROVED** [review]
Nice!

**Comment by jonathanadler** [comment]
Let's just wait for all the tests to run, and then we can merge :)

**Pull request merged**
