### PR TITLE
Migrated to svg2react-icon v3

### PR DESCRIPTION
**Pull request by Faradey27**
Screenshots
v2:
http://prntscr.com/jr6weu
http://prntscr.com/jr6wir
v3:
http://prntscr.com/jr6vbc
http://prntscr.com/jr6vht

from my perspective looks fine

### CODE REVIEW

**Comment by shlomitc** [comment]
maybe we can add some eyes tests screenshot to make sure it is not broken?
will probably need to be in a different PR

**Comment by Faradey27** [comment]
@shlomitc will create separate pull request with eyes tests and after merging it let merge this one

**Comment by alisey** [comment]
Don't merge just yet, there's a bug here: https://github.com/wix/svg2react-icon/blob/master/src/lib/svg2component.js#L16

**Comment by alisey** [comment]
Another bug here: https://github.com/wix/svg2react-icon/blob/master/src/lib/svg2component.js#L43

`${widthFromSvg}` needs to be in quotes, otherwise if the SVG doesn't have width, the compiled code is going to be this:
```
width={props.size || 1em}
```

**Comment by alisey** [comment]
Another problem here: https://github.com/wix/svg2react-icon/blob/master/src/lib/svg2component.js#L29
The size prop ends up directly on the SVG element, we should exclude it from props like this: `({size, ...props}) => {...}`

Sorry for not giving a more thorough review earlier today, I was tired and distracted.

**Comment by Faradey27** [comment]
@alisey https://github.com/wix/svg2react-icon/pull/17

**Comment by Faradey27** [comment]
Pull request update to svg2react-icon@^3.0.1 with fixes

@shlomitc

**Comment by shlomitc** [comment]
CI is failing now (issue with npm registry), let's make it pass and see that tests are running and then we can merge

**Pull request merged**
