### PR TITLE
EnhancedUniDriver - with dataHook queries

### PR DESCRIPTION
**Pull request by hepiyellow**
Enhances UniDriver with dataHook query methods.

### CODE REVIEW

**Comment by mykas** [comment]
Looks pretty great. Though I would suggest creating another PR for wix-ui-test-utils library and move the code there. As you see we have failing wix-ui-core because of that.

**Comment by hepiyellow** [comment]
@mykas The EnhancedUniDriver is in wix-ui-test-utils

**Comment by mykas** [comment]
Yes, but you modify and use it at the same time in this PR. If you separate wix-ui-test-utils changes with another PR - you could achieve green builds.

**Comment by hepiyellow** [comment]
@shlomitc If you feel like lior then you can close this.

**Comment by shlomitc** [comment]
Closing for now. let's revive it when more use cases will pop.

**Pull request closed without merging**
