### PR TITLE
docs(StylableText): use autodocs

### PR DESCRIPTION
**Pull request by argshook**

### CODE REVIEW

**Comment by shlomitc** [comment]
image

seems broken

**Comment by argshook** [comment]
@shlomitc link please. i look here,  works on my machine https://wix-wix-ui-pr-299.surge.sh/?selectedKind=Components&selectedStory=Input&full=0&addons=0&stories=1&panelRight=0

**Comment by shlomitc** [comment]
https://wix-wix-ui-pr-299.surge.sh/?selectedKind=Components&selectedStory=StylableText&full=0&addons=0&stories=1&panelRight=0

**Comment by argshook** [comment]
i was looking elsewhere for no reason...
now i see that react-docgen-typescript gives me `displayName: 'index'` who knows why. i'll investigate more tomorrow

**Comment by argshook** [comment]
Fixed! @shlomitc

**Comment by shlomitc** [comment]
Great job!

**Pull request merged**
